### ISSUE TITLE
Small bug on large strings

### ISSUE THREAD

**Issue by eflukx** [hasegaw/msgpack-mcu#2]
You'd probably never run into this on small(ish) MCU's, but still its a bug :wink: 

https://github.com/hasegaw/msgpack-mcu/blob/master/src/umsgpack.c#L409

`case 4` should read `case 3`

**Comment by hasegaw** [comment]
Thanks for catching this. I'll fix later.

**Comment by hasegaw** [comment]
Resolved in commit 2f038850. (Thanks @ryochack)
