### ISSUE TITLE
No license info in this repository

### ISSUE THREAD

**Issue by hasegaw** [hasegaw/msgpack-mcu#5]
This repository haven't stated about license because I forget to define the license at the time of first commit.
This should be licensed under MIT License, regarding the use case such as embedded stuffs.

**Comment by hasegaw** [comment]
@ryochack and @eflukx :
Could you approve MIT License for your pull requests?
Any suggestions or comments are also appreciated.

**Comment by hasegaw** [comment]
examples/arduino/umsgpack_test1.ino file includes APL2.0 license term.
It should be licensed under the new license.

**Comment by ryochack** [comment]
Yes. MIT License is good for me!

**Comment by hasegaw** [comment]
Thanks @ryochack. I'd like to wait for @eflukx's response for a while.

**Comment by eflukx** [comment]
Yes MIT would be fine indeed.

Thanks for asking,
a happy uMsgPack user.

**Comment by hasegaw** [comment]
Thanks @eflukx.

**Comment by hasegaw** [comment]
Resolved in commit 701ea3f96707a223a7e1b730567ad9cdac71b4c4
